### ISSUE TITLE
AS3600 assigning ku to zero where no axial load is present

### ISSUE THREAD

**Issue by darryllshanks** [robbievanleeuwen/concrete-properties#104]
Hi @robbievanleeuwen,
Working through the example in the documentation (https://concrete-properties.readthedocs.io/en/stable/examples/as3600.html) in a JupyterNotebook, I noted that the parameter kuo for a beam in pure bending, is incorrectly exported as 0.0000 with d_n as infinite when calculating the ultimate bending capacity. This is reflected in both my JupyterNotebook and the online documentation.

>f_ult_res, ult_res, phi = design_code.ultimate_bending_capacity()
>ult_res.print_results()
>print(f"kuo = {ult_res.k_u:.4f}")

The bending capacity 'Muo' and factored capacity 'phi.Muo' are still correct. If I set n_star to something small (0.0001), ku is comes out correctly at 0.0898.

Working through the code I believe the error may be in as3600.py line 431, where I suspect it should be "greater than or equal to".

```python
# regular calculation
elif n_design > 0:
    ult_res = self.concrete_section.ultimate_bending_capacity(theta=theta, n=n_design / phi)
```

Are you able to verify whether my understanding of what the code is doing here would still be valid with this change?

P.S. Note that kuo is correctly calculated using the more general (not code specific) module.

- **concreteproperties version**: <0.6.1>
- **Python version**: <3.10>
- **OS version and name**: <Windows 11 Home 23H2>

- [x] I am on the [latest](https://github.com/robbievanleeuwen/concrete-properties/releases/latest)
      stable concreteproperties version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/robbievanleeuwen/concrete-properties/issues)
      of this repo and believe that this is not a duplicate.
- [x] I have consulted the [documentation](https://concrete-properties.readthedocs.io/)
      for any relevant information.

**Comment by robbievanleeuwen** [comment]
Hi @darryllshanks, thanks for the issue! I'm hoping to have some time this weekend to have a quick peek at this.

**Comment by robbievanleeuwen** [comment]
Hi @darryllshanks, yes I think you've correctly spotted the missing equals sign here, thanks! If you'd like the contributor stats I'm happy for you to submit a pull-request for this fix. Otherwise I can look at updating sometime this coming weekend.

Cheers!

**Comment by darryllshanks** [comment]
Hi @robbievanleeuwen, thanks for having a look at this. I might give raising a pull request a crack as I could use the practice to understand the process works. 

Ps. Love the effort to date for both concrete-properties and section-properties. It's a great tool!
