### ISSUE TITLE
Add labels parameter for biaxial multiple diagram results

### ISSUE THREAD

**Issue by Lomarandil** [robbievanleeuwen/concrete-properties#14]
Similar to implementation for moment interaction results object

**Comment by robbievanleeuwen** [comment]
Good suggestion, will add this feature for both the 2D and current implementation of the 3D plot.

**Comment by robbievanleeuwen** [comment]
I have added labels to the 2D multiple biaxial bending plots. ``matplotlib`` seemed to struggle with labels for 3D plots so I haven't included this for now. The 3D plot will be changing in the future to a wireframe/surface so the labels will be obselete anyway.
