### ISSUE TITLE
Plot multiple biaxial bending diagrams in 2D plot

### ISSUE THREAD

**Issue by Lomarandil** [robbievanleeuwen/concrete-properties#15]
While the 3D plot is a great visualization, it's hard to use in practice. 

I'm sure that a more Python adept user would be able to create a matplotlib 2D plot with multiple biaxial bending diagrams (e.g. contours for different values of N), but I'm struggling.

It would be great if plot_multiple_diagrams for biaxial bending had a built-in option for a 2D flattened plot.

**Comment by robbievanleeuwen** [comment]
Hi @Lomarandil I agree completely.

The end goal is to create a proper 3D biaxial bending diagram (think a surface wireframe) that the user can query whether a point lies within or outside the surface and also get some kind of utilisation ratio.

For now I can add a 2D diagram which may hang around as well as another option for visulisation.

**Comment by robbievanleeuwen** [comment]
@Lomarandil I have updated the example [here](https://robbievanleeuwen.github.io/concrete-properties/notebooks/biaxial_bending.html) so you can see it's usage.

**Comment by Lomarandil** [comment]
Excellent work, thanks Robbie!
