### ISSUE TITLE
Neutral axis depth range for M-N interaction diagram not accounting for gamma effect for full section depth being in compression

### ISSUE THREAD

**Issue by Agent6-6-6** [robbievanleeuwen/concrete-properties#26]
Hi @robbievanleeuwen 

When generating the interaction diagrams, I think you should be checking the neutral axis depth is between `Zero` & the `Depth of section divided by the gamma factor`. If you want the point where the section has all of the concrete area under full compression then because you're factoring the neutral access depth by gamma (I think in your nomenclature) to work out the depth of the compression block, you need to do this.

For example otherwise as it is currently implemented for a section of say 400mm depth when factored by gamma of 0.85 in the analysis to determine the compression block depth 'a', it will only mean you're capturing analysis points from zero compression block depth to 0.85*400 = 340 compression block depth when you determine the points you're working out the moment capacity for to generate the interaction diagram. So you're missing out on data points where the compression block is between 0.85 and 1.0 times the section depth in this example.

I was trying to work out why your interaction diagrams have a much wider spaced range between the last point before the squash load and the squash load, and believe this is one of the reasons, you're missing a few data points at larger neutral axis depths (how much depends on the value of gamma). 

Hopefully that makes sense, if not let me know and I can try explain.

**Comment by Agent6-6-6** [comment]
results of a random section with gamma = 0.6 vs 0.9 to show the differences, refer specifically to the larger gap at the top of the diagram as you're not getting any points generated:
### Gamma = 0.6
![Gamma 0 6](https://user-images.githubusercontent.com/36808164/182011515-feeb00db-20af-4e7b-9e49-22aadf91b9f3.png)

### Gamma = 0.9
![Gamma 0 9](https://user-images.githubusercontent.com/36808164/182011525-fe8fbcb7-88a6-4e3a-907d-9ee7f43d3680.png)

**Comment by robbievanleeuwen** [comment]
@Agent6-6-6 great minds, I'm currently working on this! Last night I realised the way I construct interaction diagrams is very AS3600-centric so it's currently getting a bit of a rewrite. Deleting the concept of squash load and ultimate tensile load as these are AS3600 and not general terms. The analysis will begin at zero curvature (constant compressive strain) and will finish at neutral axis depth of (almost) zero. This will now allow the analysis to sweep through the entire diagram and not jump from pure bending to tension and decompression to squash.

**Comment by robbievanleeuwen** [comment]
This is what it's currently looking like. 
![image](https://user-images.githubusercontent.com/18841910/182012712-5b0400e7-6f38-46a0-bcba-273a6df59392.png)
Point A is zero curvature, point B is D / gamma and point I is zero neutral axis depth. Note that this section is asymmetric and therefore has residual moment about the centroid at full plasticity (tension & compression). I was not capturing this behaviour before. FYI here is the positive and negative plots together:
![image](https://user-images.githubusercontent.com/18841910/182012789-b98df9d4-821f-4d55-b9c2-8948ff021ffb.png)

**Comment by Agent6-6-6** [comment]
Yeah I was wondering as well why there were no points on the tension side as well but hadn't worked out why.

Looks good.
