### ISSUE TITLE
find concrete_section.ultimate_bending_capacity() needs method for max compression load check

### ISSUE THREAD

**Issue by Agent6-6-6** [robbievanleeuwen/concrete-properties#41]
Hi @robbievanleeuwen 
`concrete_section.ultimate_bending_capacity()` needs a way of detecting when you analyse a section and enter an axial load that is greater than maximum compression capacity of a cross section. Not having this ability may lead to unconservative results being accepted as being true.

This could be handled within the individual `design_code` code if easier, by checking the axial load is less than the max compression before calling `concrete_section.ultimate_bending_capacity()`. 

But I was thinking you'd be better implementing a `max_comp` similar to what you did for the generation of an M/N interaction diagram within `concrete_section.ultimate_bending_capacity()`??

**Comment by robbievanleeuwen** [comment]
Hi @Agent6-6-6.

The current implementation of ``ConcreteSection.ultimate_bending_capacity()`` prints an unhelpful warning when the brentq algorithm fails: *"brentq algorithm failed."* This generally occurs when the algorithm cannot find a neutral axis that satisfies the axial load, so if you enter a compression or tensile load outside the maximum values in the moment interaction diagram this warning will be printed.

The problem with the current implementation (apart from the unhelpful warning) is that results are still returned from the last iteration of the algorithm which are junk results. I propose that these results do not get returned and an error is raised instead.

Then there is the problem of design codes where equilibrium can be found in an unfactored case, but the result not be valid after apply capacity reduction factors (or applying the ``max_comp``). I feel like this needs to be dealt with inside the design code as its implementation is design code dependent. I may need to tweak the AS3600 implementation to catch this.

What are your thoughts on this?
