### ISSUE TITLE
Random tkinker errors when undertaking a biaxial interaction analysis

### ISSUE THREAD

**Issue by Agent6-6-6** [robbievanleeuwen/concrete-properties#42]
Hi @robbievanleeuwen 

Not sure if you've come across this, or whether it is even within the control of concrete-properties. But when running a biaxial interaction analyses, you sometimes randomly get these errors note below. It randomly freezes for a while and then throws up these errors, but the analysis always completes:-

```
Exception ignored in: <function Variable.__del__ at 0x0000021859A91D30>
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x0000021859A91D30>
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x0000021859A91D30>
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x0000021859A91D30>
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x0000021859ACF670>
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 4017, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x0000021859A91D30>
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x0000021859A91D30>
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x0000021859A91D30>
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
  ✅ Biaxial bending diagram generated                                                                                                            ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% [ 7.2030 s ]RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x0000021859A91D30>
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x0000021859ACF670>
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 4017, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
  ✅ Biaxial bending diagram generated                                                                                                            ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% [ 7.2030 s ]
```

**Comment by robbievanleeuwen** [comment]
Hi @Agent6-6-6 I have not seen these and have run the biaxial analysis plenty of times on both my computers. 

Are you doing any plotting when this happens? The only thing in *concreteproperties* that would use tkinter is *matplotlib* I think?

**Comment by Agent6-6-6** [comment]
@robbievanleeuwen, I was running a few biaxial analyses one after the other. You can see it occurs between two runs. Was only plotting at the end.

Could it be something to do with the progress bar?

**Comment by robbievanleeuwen** [comment]
I don't think ``rich`` (progress bar package) uses tkinter as it's entirely command line based. I don't really know what's happening here, is this a reproducable issue for you (i.e. occurs every time for a given script?) If so, I could try to reproduce if you have the script handy. Otherwise I'm at a loss for why tkinter is even trying to do something!

**Comment by Agent6-6-6** [comment]
@robbievanleeuwen

It seems very random when it does occur. 

It does seem to get stuck partway through the progress bar when it does occur. Maybe for 10-30 seconds it freezes with no progress, then throws out the error(s) and carries on as if nothing happened.

That's what leads me to believe it's something related to the progress bar or the underlying analysis going off the rails and having issues converging or something.

Only seems to occur on the biaxial analysis. That's the only real constant for it occurring.

**Comment by robbievanleeuwen** [comment]
Thanks @Agent6-6-6, it may be worth giving the user the option to not have the progress bar. I will implement this as a global setting and then you can see if it makes a difference.

Also didn't quite get to the end of reviewing your PR today, will try to finish tomorrow!

**Comment by robbievanleeuwen** [comment]
Also what OS & version of python (3.8 as above?) are you using? Also where are you executing the script? Terminal, jupyter, IDLE (similar error message [here](https://stackoverflow.com/questions/54293491/pysimplegui-runtimeerror-main-thread-is-not-in-main-loop)) or other?

**Comment by Agent6-6-6** [comment]
Windows 10, running in terminal from VS Code. Yes with python 3.8.

I don't recall seeing it while working up an example in jupyter come to think of it.

> Also didn't quite get to the end of reviewing your PR today, will try to finish tomorrow!
No worries. Still a bit to do at my end no doubt to address some of the questions I raised once you get into it.

**Comment by connorferster** [comment]
When running the code in terminal, matplotlib uses tkinter to display the plot I am guessing? Does matplotlib also have a QT backend that can be activated for comparison?

**Comment by robbievanleeuwen** [comment]
After a bit of a google it seems this error is *sometimes* related to issues with virtual environments or implementing a GUI. I don't think this is a reproducable error and don't think that it's related to *concreteproperties* so will be closing this one for now.
