### ISSUE TITLE
Feature request: add consideration of axial load to moment curvature analyses

### ISSUE THREAD

**Issue by Agent6-6-6** [robbievanleeuwen/concrete-properties#44]
**Is your feature request related to a problem? Please describe.**
When undertaking a moment-curvature analysis, there does not seem to be any way to undertake the analysis with an axial load applied to a member when analysing a column for example?

**Describe the solution you'd like**
Add the ability to specify an axial load so moment curvature analyses of columns can be undertaken

**Additional context**
Moment curvature response is highly dependant on the axial load applied to a member for example:-
![image](https://user-images.githubusercontent.com/36808164/190840691-b5e8ceb1-1e27-4061-8f8a-92f180a65864.png)

**Comment by robbievanleeuwen** [comment]
Hi @Agent6-6-6, yes this is on the to-do list. I am aiming to implement prestressing into *concreteproperties* so this will be a must!

**Comment by Agent6-6-6** [comment]
@robbievanleeuwen 
I've noticed as well that the way the moment curvature analysis adaptively scales the curvature step it almost always just keeps increasing the curvature in each step. so by the time you get closer to the failure point the answers get very widely spaced.

```
if moment_diff <= delta_m_min:
                        kappa_inc *= 2
                    elif moment_diff >= delta_m_max:
                        kappa_inc *= 0.5
```

To demonstrate, first image is replacing 2 with 1.01, and 0.5 with 0.99 to arbitrarily limit to a much smaller step. You can appreciate the differences in the results in the below images for the same section. So by default the answer gets cruder and crude as it proceeds and you start to miss the fundamental behaviour I think. Note the general shape and higher curvature achieved when the steps are smaller.
![Figure_1](https://user-images.githubusercontent.com/36808164/192088899-8abcfdbd-e624-477b-a75f-1c0826b29781.svg)
![Figure_2](https://user-images.githubusercontent.com/36808164/192088901-e96f0132-678e-4c2a-8a1c-17e3819224ef.svg)

It feels like the final point should always be undertaken at the failure strain. At the moment the final analysis point returned is only the point evaluated before a moment step goes over the failure strain. Which with a cruder step could be quite a bit lower than the actual true failure strain.

**Comment by Agent6-6-6** [comment]
FYI - This is probably useful for accurate stress/strain models for NZ/AU prestressing strands, it is referenced for such purposes from NZS3101 for establishing the stress/strain relationship of strand.
[PCI - Stress-Strain Modeling Of 270 ksi Low Relaxation Prestressing Strands.pdf](https://github.com/robbievanleeuwen/concrete-properties/files/9638315/PCI.-.Stress-Strain.Modeling.Of.270.ksi.Low.Relaxation.Prestressing.Strands.pdf)

**Comment by robbievanleeuwen** [comment]
@Agent6-6-6 thanks for the reference, I've also moved the above to #51.
