### ISSUE TITLE
Improve adaptive curvature step in moment-curvature analysis

### ISSUE THREAD

**Issue by robbievanleeuwen** [robbievanleeuwen/concrete-properties#51]
@Agent6-6-6:
> I've noticed as well that the way the moment curvature analysis adaptively scales the curvature step it almost always just keeps increasing the curvature in each step. so by the time you get closer to the failure point the answers get very widely spaced.

```
if moment_diff <= delta_m_min:
                        kappa_inc *= 2
                    elif moment_diff >= delta_m_max:
                        kappa_inc *= 0.5
```

>To demonstrate, first image is replacing 2 with 1.01, and 0.5 with 0.99 to arbitrarily limit to a much smaller step. You can appreciate the differences in the results in the below images for the same section. So by default the answer gets cruder and crude as it proceeds and you start to miss the fundamental behaviour I think. Note the general shape and higher curvature achieved when the steps are smaller.
![Figure_1](https://user-images.githubusercontent.com/36808164/192088899-8abcfdbd-e624-477b-a75f-1c0826b29781.svg)
![Figure_2](https://user-images.githubusercontent.com/36808164/192088901-e96f0132-678e-4c2a-8a1c-17e3819224ef.svg)

> It feels like the final point should always be undertaken at the failure strain. At the moment the final analysis point returned is only the point evaluated before a moment step goes over the failure strain. Which with a cruder step could be quite a bit lower than the actual true failure strain.

_Originally posted by @Agent6-6-6 in https://github.com/robbievanleeuwen/concrete-properties/issues/44#issuecomment-1256912356_

**Comment by robbievanleeuwen** [comment]
Hi @Agent6-6-6 thanks for the interrogation of the adaptive step. At the time I couldn't find a simple reference for this that wasn't something super complex akin to arc-length control of unstable FEM problems... so pulled this together myself and found it worked 'OK'.  I think there are two possible changes here, keen again to hear your thoughts:

1. Add additional parameter that controls how the curvature step is modified, currently hard coded to 2. Can be changed, as you have done to smaller values >=1, where 1 would be no change. Higher values allow for faster analyses e.g. to get an overall 'feel' for the behaviour, finding bugs etc. Whereas lower values allow for a more granular analaysis capturing the intricacies of the behaviour.
2. Ensure last curvature in the analysis corresponds to the failure strain. Not too sure how easy this one will be as the netural axis is constantly changing so it's not straightforward to predict at which curvature the failure strain will occur. It might be implementing an optional additional brentq algorithm that tries to hone in one this?

**Comment by Agent6-6-6** [comment]
For the second point, could you detect failure like you currently have, and then instead of exiting simply halve the last curvature step `kappa_inc` and recheck. If still failure halve again, etc, if not failure continue for another iteration, etc until your curvature step is within some small enough tolerance indicating you're 'close enough' to the final failure strain? Would just add a few extra iterations at the end of the curve I'd imagine?

For the first point, maybe also having an upper limit cap on the curvature step increment on horizontal axis would mean things don't get too crude between data points as otherwise it just increases infinitely.

Obviously anything you do adds more time to the analysis, but I guess if you can control those multipliers as inputs and maybe an upper cap on the kappa_inc then you can tune it to your individual application?

Maybe for the multipliers just specify one as an input ratio, and have the other as the inverse? i.e. if 1.25 multiplier specified, inverse would be 0.8 for the reduction to `kappa_inc`, etc.

**Comment by robbievanleeuwen** [comment]
This all seems reasonable, any suggestions on what a reasonable default max. curvature step may be?

**Comment by Agent6-6-6** [comment]
For the default maximum it might be a trade off between analysis time and things not getting too crude and running away as the curve to bigger and bigger steps as a curve goes horizontal at higher curvatures (with no axial load at least). 

If a typical plot axes is going to be in units of 1e-5 or similar, maybe 1/4 or 1/3 of the grid spacing is sufficient? 
![image](https://user-images.githubusercontent.com/36808164/195523137-e96aa359-660f-4d83-a171-f254bf994a4d.png)

I guess if axial load is considered then the plot is more likely to change at the end of the curve so would need to test I guess.

**Comment by Agent6-6-6** [comment]
@robbievanleeuwen one other useful thing to add to the generation of the moment-curvature data points would be a limit on the reduction of the strength (which could be considered a failure). For example, once you go past the peak strength the strength degrades, and set a ratio on this which if it is exceeded also creates a failure condition.

I'd imagine this could be tracked by simply comparing the maximum `mxy` moment from all the prior iterations to the current iteration value, and if it exceeds a user-defined limit a failure is flagged.

![image](https://user-images.githubusercontent.com/36808164/196372195-b2315a05-f1bc-4337-9a95-dd3cad234e6a.png)

**Comment by robbievanleeuwen** [comment]
@Agent6-6-6 I feel like this last point could probably be quite easily done by post-processing rather than building into the generic moment curvature method.

**Comment by Agent6-6-6** [comment]
OK, no worries. 

A loss of strength is a pretty common failure criteria from an analysis perspective. But like you say easy to run through results after and determine this. 

Based on other failure criteria like buckling of longitudinal bars or failure at laps also applying you're always up for some post processing potentially. 

Perhaps a built-in method to return a failure moment-curvature relationship based on these type of additional failure criteria. Apply if you want to truncate moment-curvature based on strength or other limiting strain. Probably best implemented under a particular design code to be honest.

**Comment by robbievanleeuwen** [comment]
Yes agreed, does feel like design code post-processing is the best way to deal with this. If things span multiple design codes, can always put some helper methods in the ``DesignCode`` class to prevent repetition.
