### ISSUE TITLE
Small ambiguity in the docs for net axial load definitions for ultimate_bending_capacity() methods.

### ISSUE THREAD

**Issue by Agent6-6-6** [robbievanleeuwen/concrete-properties#67]
Hi @robbievanleeuwen 

I've noted in the `AS3600` class (and by extension the NZS3101 class I've been developing following your lead), that the `ultimate_bending_capacity` method has an input `n` which is noted as being the `net axial load`.

Also, the `concrete_section` class `ultimate_bending_capacity` method has input `n` and is also described as `net axial load`. However, this one is expecting `n=n/phi` as an input so they are not quite the same thing when called from a design code method. 

One of them is not correctly defined as they are not quite the same thing, should the design code class input be renamed something different with a description like `:param n_load: axial design load/action` or something like that to reflect that it is a design action and not the net axial load if that is being defined as $\displaystyle{\frac{N^*}{\phi}}$ in `concrete_section` class?

Potentially as well, this requires expanding on the definition in the `concrete_section` class that net axial load `n` really means `net axial load, defined as axial design load/action divided by phi (n=n_load/phi)` if a non-unity $\phi$ is applicable?

Perhaps also considering renaming `n` to `n_net` further separates the two different definitions?
This would also further distinguishes where `n` might often be utilised for a counter or something like that by a user.

**Comment by robbievanleeuwen** [comment]
Thanks for picking this up @Agent6-6-6.

I think the best solution is to rename in the ``AS3600`` class to ``n_design`` as it expects N* and document accordingly.

The ``concrete_section.py`` module is code agnostic, it really just deals with calculations on a structural mechanics/material properties level. As a result, I would like to leave out any mention of load factors, design capacity factors.

**Comment by Agent6-6-6** [comment]
Yeah n_design sounds good! I'll do the same in NZS3101 class 

I think you really should mention somewhere if using as part of a design code check then n should be inclusive of inverse of any strength reduction factors or something similar for clarity.

**Comment by robbievanleeuwen** [comment]
> I think you really should mention somewhere if using as part of a design code check then n should be inclusive of inverse of any strength reduction factors or something similar for clarity.

Are you referring to in ``concrete_section.py``? I can mention something relating to being careful if using for design code checks or similar. Inclusive of inverse of phi doesn't work for all codes, e.g. AS3600 it's non-linear because phi is also a function of ``N`` and ``k_uo`` so can be a bit tricker than just inverse phi for non-zero ``N``.

**Comment by Agent6-6-6** [comment]
Yeah, I was referring to `concrete_section` for adding a warning or note in the docs.

I guess referring to it should be the "nominal" value, prior to the application of any code capacity reduction factors, partial safety factors or other design code modifiers which might be applied to achieve final design capacities. i.e dividing or multiplying as appropriate depending on how a design code might deal with this aspect.

FOr the built in design codes this will obviously be handled automatically, but someone doing something manual may misinterpret it.

I guess the thing is every code will have slightly different terminology for what we might call the nominal value, you're referring to the net axial load for example. But in NZ we'd refer to it as the 'nominal' value. But the concept is the same. Maybe adding an ::admonition.. warning in the docs with a logical explanation of how n should be used if dealing with a manual design code check?

I've updated the `NZS3101` class to change `n` to `n_design`, I think it makes it a lot clearer of the distinction between the two values. 👍 





I guess more than anything just to prevent someone from misinterpreting it, and getting incorrect results.

**Comment by Agent6-6-6** [comment]
FYI, exact same concept also applies to custom control points in moment interaction diagram when using "N" axial load type control points.
