### ISSUE TITLE
pip install doesn't include design_codes

### ISSUE THREAD

**Issue by skane88** [robbievanleeuwen/concrete-properties#71]
**Describe the bug**
I tried pip installing concreteproperties this morning and the ```design_codes``` module wasn't included. Is this a bug or is this feature still in development at this point?

**To Reproduce**
Steps to reproduce the behaviour: ```pip install concreteproperties```

**Expected behaviour**
```design_codes``` module included in installation.

**Screenshots**
![image](https://user-images.githubusercontent.com/8041753/204167670-b4e3d2dc-467d-490e-a027-c075553ba733.png)

![image](https://user-images.githubusercontent.com/8041753/204167806-42cada84-f115-491a-8897-d51ef6ea7ac1.png)

**Comment by robbievanleeuwen** [comment]
Hi @skane88 thanks for picking this up. This should now be fixed with ``v0.4.1``.

**Comment by skane88** [comment]
Thanks for the quick response - seems to work on my end. Also, thanks for this library (and sectionproperties as well).
