### ISSUE TITLE
The neutral axis should not be theta

### ISSUE THREAD

**Issue by jiandong-qiao** [robbievanleeuwen/concrete-properties#94]
- [x] I have searched the [issues](https://github.com/robbievanleeuwen/concrete-properties/issues)
      of this repo and believe that this is not a duplicate.

## Issue

In most analyses, it is assumed that the Angle between the neutral axis and x is theta, which in turn is the Angle between the resultant bending moment and the x axis. Is it correct?

**Comment by jiandong-qiao** [comment]
If not, well, most of the program needs to be rewritten

**Comment by buddyd16** [comment]
This was discussed a bit here: https://github.com/robbievanleeuwen/concrete-properties/discussions/31

If I recall correctly The P vs M curve for biaxial bending produced by concrete properties is not accurate. For Biaxial analysis users need to look at the Mx vs My plot.

**Comment by Agent6-6-6** [comment]
To add to what @buddyd16 noted, I believe the P/M curves are only accurate for fully  symmetric sections bent about principle axes.

The bones are there to solve this, just needs someone to put some time into revising the algorithm to solve for the load angle relative to neutral axis angle.

**Comment by jiandong-qiao** [comment]
robbievanleeuwen：
&nbsp; &nbsp; &nbsp; &nbsp;I was very touched to receive your reply! Thank you！
I've learned a lot from your wheels.&nbsp;In any section subject to axial force and bidirectional bending moment, the neutral axis exists. I adopted the optimization algorithm during calculation, and compared with XTRACT, the calculation result is satisfactory. Thanks again!
Qiao
